// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolFlow.Infrastructure.Data;

#nullable disable

namespace SchoolFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425000738_V4_ModulesAcademiques")]
    partial class V4_ModulesAcademiques
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EcoleId");

                    b.ToTable("AnneeScolaires");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Bulletin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("AppreciationDirecteur")
                        .HasColumnType("text");

                    b.Property<string>("AppreciationProfesseur")
                        .HasColumnType("text");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClasseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("EffectifClasse")
                        .HasColumnType("integer");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstPublie")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MoyenneGenerale")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PeriodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RangClasse")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("EleveId", "PeriodeId", "AnneeScolaireId")
                        .IsUnique();

                    b.ToTable("Bulletins");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FraisScolarite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Section")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SousSysteme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TitulaireId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.CreneauHoraire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClasseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EnseignantId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarque")
                        .HasColumnType("text");

                    b.Property<string>("Salle")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("MatiereId");

                    b.ToTable("CreneauxHoraires");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateDiscipline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Mesure")
                        .HasColumnType("text");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("NotifieParent")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SignalePar")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("EleveId");

                    b.HasIndex("SignalePar");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Ecole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeEcole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CouleurPrimaire")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CouleurSecondaire")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailDirecteur")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("MotifRejet")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomDirecteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrenomDirecteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Quartier")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("text");

                    b.Property<string>("Slogan")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SousSysteme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelephoneDirecteur")
                        .HasColumnType("text");

                    b.Property<string>("TelephonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelephoneSecondaire")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeSecteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodeEcole")
                        .IsUnique();

                    b.ToTable("Ecoles");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<Guid?>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClasseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactUrgence")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupeSanguin")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nationalite")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarques")
                        .HasColumnType("text");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("FamilleId");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Enseignant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnneesExperience")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("Specialite")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.EvaluationPlanifiee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClasseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstPubliee")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NoteSur")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PeriodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Examen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Examens");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailMere")
                        .HasColumnType("text");

                    b.Property<string>("EmailPere")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("NomMere")
                        .HasColumnType("text");

                    b.Property<string>("NomPere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrenomMere")
                        .HasColumnType("text");

                    b.Property<string>("PrenomPere")
                        .HasColumnType("text");

                    b.Property<string>("ProfessionMere")
                        .HasColumnType("text");

                    b.Property<string>("ProfessionPere")
                        .HasColumnType("text");

                    b.Property<string>("QuartierCommune")
                        .HasColumnType("text");

                    b.Property<string>("TelephoneMere")
                        .HasColumnType("text");

                    b.Property<string>("TelephonePere")
                        .HasColumnType("text");

                    b.Property<string>("TelephonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelephoneSecondaire")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Familles");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PeriodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarques")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeFraisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("TypeFraisId");

                    b.ToTable("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.InscriptionExamen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Admis")
                        .HasColumnType("boolean");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamenId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Mention")
                        .HasColumnType("text");

                    b.Property<decimal?>("MoyenneExamen")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NumeroCandidat")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("ExamenId", "EleveId")
                        .IsUnique();

                    b.ToTable("InscriptionsExamen");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.LigneBulletin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppreciationEnseignant")
                        .HasColumnType("text");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BulletinId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MoyenneClasse")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MoyenneMatiere")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MoyennePonderee")
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BulletinId");

                    b.HasIndex("MatiereId");

                    b.ToTable("LignesBulletin");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SousSysteme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.MatiereEnseignant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClasseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnseignantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("EnseignantId", "MatiereId", "ClasseId", "AnneeScolaireId")
                        .IsUnique();

                    b.ToTable("MatiereEnseignants");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstPubliee")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NoteSur")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PeriodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnregistrePar")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroPaiement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnregistrePar");

                    b.HasIndex("FamilleId");

                    b.HasIndex("NumeroPaiement")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Periodes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("GenerationAutomatique")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsObligatoire")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MontantsParNiveau")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TypeFrais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EcoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EcoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FraisId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MontantVentile")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaiementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarque")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("FraisId");

                    b.HasIndex("PaiementId");

                    b.ToTable("VentilationsPaiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Ecole", "Ecole")
                        .WithMany("AnneeScolaires")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecole");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Bulletin", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Eleve");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Classes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.CreneauHoraire", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Enseignant", "Enseignant")
                        .WithMany("Creneaux")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Creneaux")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Discipline", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany()
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "SignaleParUtilisateur")
                        .WithMany()
                        .HasForeignKey("SignalePar")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Eleve");

                    b.Navigation("SignaleParUtilisateur");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Eleves")
                        .HasForeignKey("AnneeScolaireId");

                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany("Eleves")
                        .HasForeignKey("ClasseId");

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Eleves")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Classe");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Enseignant", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.EvaluationPlanifiee", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Evaluations")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Matiere");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Examen", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany()
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Frais")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.TypeFrais", "TypeFrais")
                        .WithMany("Frais")
                        .HasForeignKey("TypeFraisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Periode");

                    b.Navigation("TypeFrais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.InscriptionExamen", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Examen", "Examen")
                        .WithMany("Inscrits")
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.LigneBulletin", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Bulletin", "Bulletin")
                        .WithMany("Lignes")
                        .HasForeignKey("BulletinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bulletin");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.MatiereEnseignant", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Enseignant", "Enseignant")
                        .WithMany("Matieres")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Notes")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.EvaluationPlanifiee", "Evaluation")
                        .WithMany("Notes")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Notes")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Evaluation");

                    b.Navigation("Matiere");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "EnregistreParUtilisateur")
                        .WithMany()
                        .HasForeignKey("EnregistrePar")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Paiements")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnregistreParUtilisateur");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Periodes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Ecole", "Ecole")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ecole");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.Frais", "Frais")
                        .WithMany("Ventilations")
                        .HasForeignKey("FraisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Paiement", "Paiement")
                        .WithMany("Ventilations")
                        .HasForeignKey("PaiementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Frais");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Eleves");

                    b.Navigation("Periodes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Bulletin", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Ecole", b =>
                {
                    b.Navigation("AnneeScolaires");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Navigation("Frais");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Enseignant", b =>
                {
                    b.Navigation("Creneaux");

                    b.Navigation("Matieres");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.EvaluationPlanifiee", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Examen", b =>
                {
                    b.Navigation("Inscrits");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Navigation("Eleves");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Navigation("Creneaux");

                    b.Navigation("Evaluations");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Navigation("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
