// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolFlow.Infrastructure.Data;

#nullable disable

namespace SchoolFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AnneeScolaires");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 32, 206, DateTimeKind.Utc).AddTicks(3693),
                            DateDebut = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateFin = new DateTime(2025, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsArchived = false,
                            Libelle = "2024-2025"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Section")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d458761-1f99-4d89-bb10-e55145a43c9b"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "CP",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9213),
                            IsArchived = false,
                            Niveau = "CP",
                            Nom = "CP"
                        },
                        new
                        {
                            Id = new Guid("5b7977c3-3a53-44ec-8144-9279d2743188"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "CE1",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9242),
                            IsArchived = false,
                            Niveau = "CE1",
                            Nom = "CE1"
                        },
                        new
                        {
                            Id = new Guid("5e3648b8-1ecd-4c50-9ccb-96d6ab8748d5"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "CE2",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9253),
                            IsArchived = false,
                            Niveau = "CE2",
                            Nom = "CE2"
                        },
                        new
                        {
                            Id = new Guid("f7f2edc1-c130-4d4d-8e03-c3aff661c85f"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "CM1",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9285),
                            IsArchived = false,
                            Niveau = "CM1",
                            Nom = "CM1"
                        },
                        new
                        {
                            Id = new Guid("e55206c2-d4e4-4830-9bd4-1de84ec1a01a"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "CM2",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9293),
                            IsArchived = false,
                            Niveau = "CM2",
                            Nom = "CM2"
                        },
                        new
                        {
                            Id = new Guid("d51e956c-991d-473e-ad63-deeca3421457"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "SIXIEME",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9537),
                            IsArchived = false,
                            Niveau = "Sixieme",
                            Nom = "6ème"
                        },
                        new
                        {
                            Id = new Guid("c5a759a4-47c1-49b3-9e79-b1a6b5f1d5b6"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "CINQUIEME",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9593),
                            IsArchived = false,
                            Niveau = "Cinquieme",
                            Nom = "5ème"
                        },
                        new
                        {
                            Id = new Guid("e02cd263-6608-4488-859a-e640e5a12a08"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "QUATRIEME",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9617),
                            IsArchived = false,
                            Niveau = "Quatrieme",
                            Nom = "4ème"
                        },
                        new
                        {
                            Id = new Guid("485288eb-599f-4cc4-b69b-94679798cfab"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "TROISIEME",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9628),
                            IsArchived = false,
                            Niveau = "Troisieme",
                            Nom = "3ème"
                        },
                        new
                        {
                            Id = new Guid("efaa9843-efbb-4d5a-9b03-a1c1200a8e82"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "SECONDE",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9643),
                            IsArchived = false,
                            Niveau = "Seconde",
                            Nom = "2nde"
                        },
                        new
                        {
                            Id = new Guid("77a717f6-a8ac-4fdf-85f5-743c0fbff36a"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "PREMIERE",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9654),
                            IsArchived = false,
                            Niveau = "Premiere",
                            Nom = "1ère"
                        },
                        new
                        {
                            Id = new Guid("dfb98b57-4a32-4e27-9133-231b31ad94f5"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CapaciteMax = 60,
                            Code = "TERMINALE",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(9670),
                            IsArchived = false,
                            Niveau = "Terminale",
                            Nom = "Tle"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<Guid?>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClasseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactUrgence")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupeSanguin")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nationalite")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarques")
                        .HasColumnType("text");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("FamilleId");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailMere")
                        .HasColumnType("text");

                    b.Property<string>("EmailPere")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("NomMere")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomPere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrenomMere")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrenomPere")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfessionMere")
                        .HasColumnType("text");

                    b.Property<string>("ProfessionPere")
                        .HasColumnType("text");

                    b.Property<string>("QuartierCommune")
                        .HasColumnType("text");

                    b.Property<string>("TelephoneMere")
                        .HasColumnType("text");

                    b.Property<string>("TelephonePere")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelephonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelephoneSecondaire")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Familles");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("PeriodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarques")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeFraisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("TypeFraisId");

                    b.ToTable("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MatiereId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NoteSur")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid?>("PeriodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnregistrePar")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NumeroPaiement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnregistrePar");

                    b.HasIndex("FamilleId");

                    b.HasIndex("NumeroPaiement")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Periodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("815cb673-33b7-4a2c-9ee6-2e6ef7e3aff2"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 32, 206, DateTimeKind.Utc).AddTicks(4246),
                            DateDebut = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateFin = new DateTime(2024, 12, 15, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Libelle = "Trimestre 1",
                            Numero = 1,
                            Type = "Trimestre"
                        },
                        new
                        {
                            Id = new Guid("963eb957-0ddc-424f-9bd9-a24d22be6b65"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 32, 206, DateTimeKind.Utc).AddTicks(4255),
                            DateDebut = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateFin = new DateTime(2025, 3, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Libelle = "Trimestre 2",
                            Numero = 2,
                            Type = "Trimestre"
                        },
                        new
                        {
                            Id = new Guid("4dd1d48c-5b19-4541-b34c-4bbef93a9759"),
                            AnneeScolaireId = new Guid("3788567f-f9cb-47f3-8779-29ba4bbda764"),
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 32, 206, DateTimeKind.Utc).AddTicks(4260),
                            DateDebut = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateFin = new DateTime(2025, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Libelle = "Trimestre 3",
                            Numero = 3,
                            Type = "Trimestre"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("GenerationAutomatique")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsObligatoire")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MontantsParNiveau")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TypeFrais");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a84b52b7-79f6-47ea-b5b8-852e75a8ccd7"),
                            Categorie = "Inscription",
                            Code = "INSC",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 394, DateTimeKind.Utc).AddTicks(896),
                            GenerationAutomatique = true,
                            IsArchived = false,
                            IsObligatoire = true,
                            IsRecurrent = false,
                            Libelle = "Frais d'inscription",
                            MontantsParNiveau = "{\"CP\":5000,\"CE1\":5000,\"CE2\":5000,\"CM1\":5000,\"CM2\":5000,\"Sixieme\":5000,\"Cinquieme\":5000,\"Quatrieme\":5000,\"Troisieme\":5000,\"Seconde\":5000,\"Premiere\":5000,\"Terminale\":5000}"
                        },
                        new
                        {
                            Id = new Guid("c0cb0248-510c-469b-829f-80e84954c760"),
                            Categorie = "Scolarite",
                            Code = "SCOL",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 394, DateTimeKind.Utc).AddTicks(908),
                            Description = "Frais de scolarité trimestriel",
                            GenerationAutomatique = true,
                            IsArchived = false,
                            IsObligatoire = true,
                            IsRecurrent = true,
                            Libelle = "Scolarité",
                            MontantsParNiveau = "{\"CP\":60000,\"CE1\":60000,\"CE2\":60000,\"CM1\":70000,\"CM2\":70000,\"Sixieme\":80000,\"Cinquieme\":80000,\"Quatrieme\":85000,\"Troisieme\":85000,\"Seconde\":90000,\"Premiere\":90000,\"Terminale\":90000}"
                        },
                        new
                        {
                            Id = new Guid("7369786d-688d-4567-8077-fca4a56c1d0d"),
                            Categorie = "Cantine",
                            Code = "CANT",
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 394, DateTimeKind.Utc).AddTicks(916),
                            Description = "Frais de cantine mensuel",
                            GenerationAutomatique = false,
                            IsArchived = false,
                            IsObligatoire = false,
                            IsRecurrent = true,
                            Libelle = "Cantine",
                            MontantsParNiveau = "{\"CP\":15000,\"CE1\":15000,\"CE2\":15000,\"CM1\":15000,\"CM2\":15000,\"Sixieme\":15000,\"Cinquieme\":15000,\"Quatrieme\":15000,\"Troisieme\":15000,\"Seconde\":15000,\"Premiere\":15000,\"Terminale\":15000}"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdd7b3e0-207c-4971-9daf-adaa1cab13d7"),
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 32, 519, DateTimeKind.Utc).AddTicks(885),
                            Email = "admin@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Administrateur",
                            PasswordHash = "$2a$11$yFAzr72u0K4v1h/0Ov.Qcuat/1IUbr1cILHMYtq/Q1pYXj9O/WAiC",
                            Prenom = "Système",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("eee4d866-e0f1-40f5-8338-6b74b618270d"),
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 32, 809, DateTimeKind.Utc).AddTicks(4583),
                            Email = "directeur@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Durand",
                            PasswordHash = "$2a$11$ledenWoLZC6bLPJ5jZoRdepLtojCoen3HxzZOGpoUYVHXfK06DBSC",
                            Prenom = "Marie",
                            Role = "Directeur",
                            Username = "directeur"
                        },
                        new
                        {
                            Id = new Guid("39fecf1d-e759-45b8-89a8-f6164ae87a77"),
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 96, DateTimeKind.Utc).AddTicks(1899),
                            Email = "comptable@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Martin",
                            PasswordHash = "$2a$11$CARvhJpSYWcRM4Bb7hDqE.XT6.PYgiS.Mzhfamy0eogKMdDiloBMe",
                            Prenom = "Sophie",
                            Role = "Comptable",
                            Username = "comptable"
                        },
                        new
                        {
                            Id = new Guid("6f57a332-7a39-4f85-ab09-35fcd925f449"),
                            CreatedAt = new DateTime(2026, 3, 3, 22, 31, 33, 393, DateTimeKind.Utc).AddTicks(8518),
                            Email = "secretaire@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Leroy",
                            PasswordHash = "$2a$11$iTk0IVpr4XpY1Il9jnkzlu8XDxvLuWIZbcXYAXjoAsD3pwfK7QLXi",
                            Prenom = "Paul",
                            Role = "Secretaire",
                            Username = "secretaire"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FraisId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MontantVentile")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PaiementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarque")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("FraisId");

                    b.HasIndex("PaiementId");

                    b.ToTable("VentilationsPaiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Classes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Eleves")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany("Eleves")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Eleves")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Classe");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Frais")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.TypeFrais", "TypeFrais")
                        .WithMany("Frais")
                        .HasForeignKey("TypeFraisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Periode");

                    b.Navigation("TypeFrais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Notes")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Notes")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "EnregistreParUtilisateur")
                        .WithMany()
                        .HasForeignKey("EnregistrePar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Paiements")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnregistreParUtilisateur");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Periodes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Frais", "Frais")
                        .WithMany("Ventilations")
                        .HasForeignKey("FraisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.Paiement", "Paiement")
                        .WithMany("Ventilations")
                        .HasForeignKey("PaiementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Frais");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Eleves");

                    b.Navigation("Periodes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Navigation("Frais");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Navigation("Eleves");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Navigation("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
