// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolFlow.Infrastructure.Data;

#nullable disable

namespace SchoolFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218124936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AnneeScolaires");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 29, 925, DateTimeKind.Utc).AddTicks(1765),
                            DateDebut = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsArchived = false,
                            Libelle = "2024-2025"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Section")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("396f3e27-e879-4e77-ac5a-d82eaeb2c47f"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "CP",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8070),
                            IsArchived = false,
                            Niveau = "CP",
                            Nom = "CP"
                        },
                        new
                        {
                            Id = new Guid("44de80f0-81bd-4a04-aecd-1d4fb23a6480"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "CE1",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8100),
                            IsArchived = false,
                            Niveau = "CE1",
                            Nom = "CE1"
                        },
                        new
                        {
                            Id = new Guid("a1597343-e4dd-4f34-ae06-9fc18980ce2d"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "CE2",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8112),
                            IsArchived = false,
                            Niveau = "CE2",
                            Nom = "CE2"
                        },
                        new
                        {
                            Id = new Guid("6b343a4e-da14-469d-8318-6bc9e1974648"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "CM1",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8158),
                            IsArchived = false,
                            Niveau = "CM1",
                            Nom = "CM1"
                        },
                        new
                        {
                            Id = new Guid("434526d5-d24c-47b5-825a-77f1ac49b80c"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "CM2",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8175),
                            IsArchived = false,
                            Niveau = "CM2",
                            Nom = "CM2"
                        },
                        new
                        {
                            Id = new Guid("3fb775e4-dbe3-4bee-a7bd-2cbf6690dc5f"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "SIXIEME",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8231),
                            IsArchived = false,
                            Niveau = "Sixieme",
                            Nom = "6ème"
                        },
                        new
                        {
                            Id = new Guid("22234eb4-a686-4e41-b90f-f479ffafbd53"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "CINQUIEME",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8293),
                            IsArchived = false,
                            Niveau = "Cinquieme",
                            Nom = "5ème"
                        },
                        new
                        {
                            Id = new Guid("7839b468-6cf3-419d-b6a9-30ac09127f96"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "QUATRIEME",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8316),
                            IsArchived = false,
                            Niveau = "Quatrieme",
                            Nom = "4ème"
                        },
                        new
                        {
                            Id = new Guid("ccdc6543-ca4d-4d41-9139-2105bc5ab7bb"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "TROISIEME",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8327),
                            IsArchived = false,
                            Niveau = "Troisieme",
                            Nom = "3ème"
                        },
                        new
                        {
                            Id = new Guid("3468793f-ea19-4058-bf64-431d8ec0bb0d"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "SECONDE",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8342),
                            IsArchived = false,
                            Niveau = "Seconde",
                            Nom = "2nde"
                        },
                        new
                        {
                            Id = new Guid("a098cf9c-5c90-4faa-b715-5c4805eeb8fc"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "PREMIERE",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8355),
                            IsArchived = false,
                            Niveau = "Premiere",
                            Nom = "1ère"
                        },
                        new
                        {
                            Id = new Guid("c73fd978-80b0-4f0f-91c2-66c0ab2315be"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CapaciteMax = 60,
                            Code = "TERMINALE",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(8371),
                            IsArchived = false,
                            Niveau = "Terminale",
                            Nom = "Tle"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClasseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactUrgence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupeSanguin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationalite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("FamilleId");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPere")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("NomMere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomPere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrenomMere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrenomPere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfessionMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionPere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuartierCommune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephonePere")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelephonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelephoneSecondaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Familles");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeFraisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("TypeFraisId");

                    b.ToTable("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Coefficient")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EleveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MatiereId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NoteSur")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("PeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnregistrePar")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroPaiement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnregistrePar");

                    b.HasIndex("FamilleId");

                    b.HasIndex("NumeroPaiement")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Periodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e35c96b7-f8f8-4845-80c7-393e6582eedb"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 29, 925, DateTimeKind.Utc).AddTicks(2495),
                            DateDebut = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 1",
                            Numero = 1,
                            Type = "Trimestre"
                        },
                        new
                        {
                            Id = new Guid("c39b2291-1b35-4726-a853-23030a2955b1"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 29, 925, DateTimeKind.Utc).AddTicks(2503),
                            DateDebut = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 2",
                            Numero = 2,
                            Type = "Trimestre"
                        },
                        new
                        {
                            Id = new Guid("79f89853-0522-4f0c-8a9d-2fab1ecf20b5"),
                            AnneeScolaireId = new Guid("49ba4273-ba81-46e2-a044-47b46554cdcd"),
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 29, 925, DateTimeKind.Utc).AddTicks(2507),
                            DateDebut = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 3",
                            Numero = 3,
                            Type = "Trimestre"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GenerationAutomatique")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsObligatoire")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MontantsParNiveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TypeFrais");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f02d7a06-dfa7-4699-b070-653727fab283"),
                            Categorie = "Inscription",
                            Code = "INSC",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 31, DateTimeKind.Utc).AddTicks(288),
                            GenerationAutomatique = true,
                            IsArchived = false,
                            IsObligatoire = true,
                            IsRecurrent = false,
                            Libelle = "Frais d'inscription",
                            MontantsParNiveau = "{\"CP\":5000,\"CE1\":5000,\"CE2\":5000,\"CM1\":5000,\"CM2\":5000,\"Sixieme\":5000,\"Cinquieme\":5000,\"Quatrieme\":5000,\"Troisieme\":5000,\"Seconde\":5000,\"Premiere\":5000,\"Terminale\":5000}"
                        },
                        new
                        {
                            Id = new Guid("91bb45e7-6e26-47a8-a74d-f0c2c46a1294"),
                            Categorie = "Scolarite",
                            Code = "SCOL",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 31, DateTimeKind.Utc).AddTicks(296),
                            Description = "Frais de scolarité trimestriel",
                            GenerationAutomatique = true,
                            IsArchived = false,
                            IsObligatoire = true,
                            IsRecurrent = true,
                            Libelle = "Scolarité",
                            MontantsParNiveau = "{\"CP\":60000,\"CE1\":60000,\"CE2\":60000,\"CM1\":70000,\"CM2\":70000,\"Sixieme\":80000,\"Cinquieme\":80000,\"Quatrieme\":85000,\"Troisieme\":85000,\"Seconde\":90000,\"Premiere\":90000,\"Terminale\":90000}"
                        },
                        new
                        {
                            Id = new Guid("790fa98b-e947-4c19-b1d6-3cd1b63208e4"),
                            Categorie = "Cantine",
                            Code = "CANT",
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 31, DateTimeKind.Utc).AddTicks(302),
                            Description = "Frais de cantine mensuel",
                            GenerationAutomatique = false,
                            IsArchived = false,
                            IsObligatoire = false,
                            IsRecurrent = true,
                            Libelle = "Cantine",
                            MontantsParNiveau = "{\"CP\":15000,\"CE1\":15000,\"CE2\":15000,\"CM1\":15000,\"CM2\":15000,\"Sixieme\":15000,\"Cinquieme\":15000,\"Quatrieme\":15000,\"Troisieme\":15000,\"Seconde\":15000,\"Premiere\":15000,\"Terminale\":15000}"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4805e2e0-a55b-4042-9257-f377c5afc201"),
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 30, 207, DateTimeKind.Utc).AddTicks(7042),
                            Email = "admin@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Administrateur",
                            PasswordHash = "$2a$11$kGyw90OXwsLJ9og5wnSjLucOu4C.43zhE8dLUsPQGcnhp9pvhOotG",
                            Prenom = "Système",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("0a00556b-f5f0-4f6a-beca-90dc07a827ff"),
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 30, 479, DateTimeKind.Utc).AddTicks(5246),
                            Email = "directeur@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Durand",
                            PasswordHash = "$2a$11$nLJUJcrV97J3hAJBNhMg8OrEAFuautiqLpOvQwXIBKfjx1Ow5lARK",
                            Prenom = "Marie",
                            Role = "Directeur",
                            Username = "directeur"
                        },
                        new
                        {
                            Id = new Guid("87cae480-fb8c-4d41-98ea-eb8df3c9ba7c"),
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 30, 757, DateTimeKind.Utc).AddTicks(7285),
                            Email = "comptable@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Martin",
                            PasswordHash = "$2a$11$GNbf6QSQ.9cB4awrYnKi7ufUJlnXTj8zmSN8W8FPfqB4hZC/wI1TW",
                            Prenom = "Sophie",
                            Role = "Comptable",
                            Username = "comptable"
                        },
                        new
                        {
                            Id = new Guid("d080b4b5-1314-472f-9cbc-3ef83430ce56"),
                            CreatedAt = new DateTime(2025, 12, 18, 12, 49, 31, 30, DateTimeKind.Utc).AddTicks(7434),
                            Email = "secretaire@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Leroy",
                            PasswordHash = "$2a$11$gpJiQcIQuJ60pIA5rx/.f.0ySSoWYNOXtqDSFt5DyW1.MLnKF1mTW",
                            Prenom = "Paul",
                            Role = "Secretaire",
                            Username = "secretaire"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FraisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontantVentile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaiementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarque")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("FraisId");

                    b.HasIndex("PaiementId");

                    b.ToTable("VentilationsPaiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Classes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Eleves")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany("Eleves")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Eleves")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Classe");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Frais")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.TypeFrais", "TypeFrais")
                        .WithMany("Frais")
                        .HasForeignKey("TypeFraisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Periode");

                    b.Navigation("TypeFrais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Notes")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Notes")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "EnregistreParUtilisateur")
                        .WithMany()
                        .HasForeignKey("EnregistrePar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Paiements")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnregistreParUtilisateur");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Periodes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Frais", "Frais")
                        .WithMany("Ventilations")
                        .HasForeignKey("FraisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.Paiement", "Paiement")
                        .WithMany("Ventilations")
                        .HasForeignKey("PaiementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Frais");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Eleves");

                    b.Navigation("Periodes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Navigation("Frais");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Navigation("Eleves");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Navigation("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
