// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolFlow.Infrastructure.Data;

#nullable disable

namespace SchoolFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AnneeScolaires");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 7, 248, DateTimeKind.Utc).AddTicks(6736),
                            DateDebut = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsArchived = false,
                            Libelle = "2024-2025"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Section")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89695367-a589-4783-8e92-7d994f9024cc"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "CP",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(79),
                            IsArchived = false,
                            Niveau = "CP",
                            Nom = "CP"
                        },
                        new
                        {
                            Id = new Guid("8c1df256-b401-4bc6-8c7a-c1b74e02c618"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "CE1",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(110),
                            IsArchived = false,
                            Niveau = "CE1",
                            Nom = "CE1"
                        },
                        new
                        {
                            Id = new Guid("92eaeb5a-c83b-4187-a830-75a247b1353b"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "CE2",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(147),
                            IsArchived = false,
                            Niveau = "CE2",
                            Nom = "CE2"
                        },
                        new
                        {
                            Id = new Guid("f6d13458-6e2c-4790-bc01-b293d5a33975"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "CM1",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(161),
                            IsArchived = false,
                            Niveau = "CM1",
                            Nom = "CM1"
                        },
                        new
                        {
                            Id = new Guid("3adfa213-1689-4ab0-97a0-b30bc4c52c73"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "CM2",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(174),
                            IsArchived = false,
                            Niveau = "CM2",
                            Nom = "CM2"
                        },
                        new
                        {
                            Id = new Guid("5f18d29b-689e-47fa-9836-ff3b34eea14f"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "SIXIEME",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(208),
                            IsArchived = false,
                            Niveau = "Sixieme",
                            Nom = "6ème"
                        },
                        new
                        {
                            Id = new Guid("cce44d79-8b86-46e4-acc4-373c941c57f7"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "CINQUIEME",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(234),
                            IsArchived = false,
                            Niveau = "Cinquieme",
                            Nom = "5ème"
                        },
                        new
                        {
                            Id = new Guid("144ada19-4991-4261-b0c1-045bce67fc1f"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "QUATRIEME",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(246),
                            IsArchived = false,
                            Niveau = "Quatrieme",
                            Nom = "4ème"
                        },
                        new
                        {
                            Id = new Guid("84dad474-0c3f-4c18-ba6d-9a708935e49b"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "TROISIEME",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(256),
                            IsArchived = false,
                            Niveau = "Troisieme",
                            Nom = "3ème"
                        },
                        new
                        {
                            Id = new Guid("3f435c70-859f-4585-8d9f-1fe91263b745"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "SECONDE",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(267),
                            IsArchived = false,
                            Niveau = "Seconde",
                            Nom = "2nde"
                        },
                        new
                        {
                            Id = new Guid("1ac9af0f-b51d-4dd8-b530-899e554308b1"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "PREMIERE",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(282),
                            IsArchived = false,
                            Niveau = "Premiere",
                            Nom = "1ère"
                        },
                        new
                        {
                            Id = new Guid("eaadf8f5-998a-4105-a20a-a169ce9e83ff"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CapaciteMax = 40,
                            Code = "TERMINALE",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(291),
                            IsArchived = false,
                            Niveau = "Terminale",
                            Nom = "Tle"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClasseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactUrgence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupeSanguin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationalite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("FamilleId");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPere")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("NomMere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomPere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrenomMere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrenomPere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfessionMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionPere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuartierCommune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephonePere")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelephonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelephoneSecondaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Familles");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypeFraisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("TypeFraisId");

                    b.ToTable("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Coefficient")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatiereId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NoteSur")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnregistrePar")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroPaiement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnregistrePar");

                    b.HasIndex("FamilleId");

                    b.HasIndex("NumeroPaiement")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Periodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaa9ca46-5eca-485f-964c-bc36a3a1b51c"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 7, 248, DateTimeKind.Utc).AddTicks(7561),
                            DateDebut = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 1",
                            Numero = 1,
                            Type = "Trimestre"
                        },
                        new
                        {
                            Id = new Guid("2e8bf0fe-2652-41a6-9c4d-1665d8a752e0"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 7, 248, DateTimeKind.Utc).AddTicks(7591),
                            DateDebut = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 2",
                            Numero = 2,
                            Type = "Trimestre"
                        },
                        new
                        {
                            Id = new Guid("d98967b9-d30e-421d-bc11-c24936347e6b"),
                            AnneeScolaireId = new Guid("b659f064-efea-4080-b440-64f46624034d"),
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 7, 248, DateTimeKind.Utc).AddTicks(7596),
                            DateDebut = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 3",
                            Numero = 3,
                            Type = "Trimestre"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GenerationAutomatique")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsObligatoire")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MontantsParNiveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TypeFrais");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d78f55a-2937-48b0-9567-7b87b255a939"),
                            Categorie = "Inscription",
                            Code = "INSC",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(1884),
                            GenerationAutomatique = true,
                            IsArchived = false,
                            IsObligatoire = true,
                            IsRecurrent = false,
                            Libelle = "Frais d'inscription",
                            MontantsParNiveau = "{\"CP\":5000,\"CE1\":5000,\"CE2\":5000,\"CM1\":5000,\"CM2\":5000,\"Sixieme\":5000,\"Cinquieme\":5000,\"Quatrieme\":5000,\"Troisieme\":5000,\"Seconde\":5000,\"Premiere\":5000,\"Terminale\":5000}"
                        },
                        new
                        {
                            Id = new Guid("094e9e46-6cf0-4b0b-aca7-514fcf3d4897"),
                            Categorie = "Scolarite",
                            Code = "SCOL",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(1893),
                            Description = "Frais de scolarité trimestriel",
                            GenerationAutomatique = true,
                            IsArchived = false,
                            IsObligatoire = true,
                            IsRecurrent = true,
                            Libelle = "Scolarité",
                            MontantsParNiveau = "{\"CP\":60000,\"CE1\":60000,\"CE2\":60000,\"CM1\":70000,\"CM2\":70000,\"Sixieme\":80000,\"Cinquieme\":80000,\"Quatrieme\":85000,\"Troisieme\":85000,\"Seconde\":90000,\"Premiere\":90000,\"Terminale\":90000}"
                        },
                        new
                        {
                            Id = new Guid("a5b21246-bd82-4c04-95d2-f3752f1801d1"),
                            Categorie = "Cantine",
                            Code = "CANT",
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 416, DateTimeKind.Utc).AddTicks(1933),
                            Description = "Frais de cantine mensuel",
                            GenerationAutomatique = false,
                            IsArchived = false,
                            IsObligatoire = false,
                            IsRecurrent = true,
                            Libelle = "Cantine",
                            MontantsParNiveau = "{\"CP\":15000,\"CE1\":15000,\"CE2\":15000,\"CM1\":15000,\"CM2\":15000,\"Sixieme\":15000,\"Cinquieme\":15000,\"Quatrieme\":15000,\"Troisieme\":15000,\"Seconde\":15000,\"Premiere\":15000,\"Terminale\":15000}"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0adb616-893b-4767-89d5-a3cbaa6b29f7"),
                            CreatedAt = new DateTime(2025, 12, 11, 14, 3, 8, 415, DateTimeKind.Utc).AddTicks(8839),
                            Email = "admin@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Administrateur",
                            PasswordHash = "$2a$11$3y2kbFt4EdZZWxvCq1C4muosp5Juf1IasLotnXxSTvQB4IpUhteEi",
                            Prenom = "Système",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FraisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontantVentile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaiementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FraisId");

                    b.HasIndex("PaiementId");

                    b.ToTable("VentilationsPaiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Classes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Eleves")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany("Eleves")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Eleves")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Classe");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Frais")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.TypeFrais", "TypeFrais")
                        .WithMany("Frais")
                        .HasForeignKey("TypeFraisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Periode");

                    b.Navigation("TypeFrais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Notes")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Notes")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "EnregistreParUtilisateur")
                        .WithMany()
                        .HasForeignKey("EnregistrePar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Paiements")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnregistreParUtilisateur");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Periodes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Frais", "Frais")
                        .WithMany("Ventilations")
                        .HasForeignKey("FraisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Paiement", "Paiement")
                        .WithMany("Ventilations")
                        .HasForeignKey("PaiementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frais");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Eleves");

                    b.Navigation("Periodes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Navigation("Frais");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Navigation("Eleves");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Navigation("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
