// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolFlow.Infrastructure.Data;

#nullable disable

namespace SchoolFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AnneeScolaires");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 30, 149, DateTimeKind.Utc).AddTicks(2586),
                            DateDebut = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsArchived = false,
                            Libelle = "2024-2025"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Section")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("760b3151-b9c1-47f1-b160-c440f0e80da2"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "CP",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(2929),
                            IsArchived = false,
                            Niveau = "CP",
                            Nom = "CP"
                        },
                        new
                        {
                            Id = new Guid("98511974-fef5-4757-88c5-1976a0116a97"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "CE1",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(2965),
                            IsArchived = false,
                            Niveau = "CE1",
                            Nom = "CE1"
                        },
                        new
                        {
                            Id = new Guid("5b9898a3-2df1-4408-861f-c5c48570e07d"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "CE2",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(2979),
                            IsArchived = false,
                            Niveau = "CE2",
                            Nom = "CE2"
                        },
                        new
                        {
                            Id = new Guid("ba8857c1-f71c-4d7e-8416-0f9c3363f7b6"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "CM1",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(2992),
                            IsArchived = false,
                            Niveau = "CM1",
                            Nom = "CM1"
                        },
                        new
                        {
                            Id = new Guid("6d83f47c-44bb-455f-accd-30108eeceee4"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "CM2",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3010),
                            IsArchived = false,
                            Niveau = "CM2",
                            Nom = "CM2"
                        },
                        new
                        {
                            Id = new Guid("e1aec637-fc69-4e40-b047-41acbd35669a"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "SIXIEME",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3049),
                            IsArchived = false,
                            Niveau = "Sixieme",
                            Nom = "6ème"
                        },
                        new
                        {
                            Id = new Guid("b33cf9a1-78ac-414e-88dd-356c9422b470"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "CINQUIEME",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3098),
                            IsArchived = false,
                            Niveau = "Cinquieme",
                            Nom = "5ème"
                        },
                        new
                        {
                            Id = new Guid("f13f0755-a602-4584-8c3b-d03d6dbe36ef"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "QUATRIEME",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3110),
                            IsArchived = false,
                            Niveau = "Quatrieme",
                            Nom = "4ème"
                        },
                        new
                        {
                            Id = new Guid("011bd139-809a-4959-9bb7-0c736549a745"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "TROISIEME",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3124),
                            IsArchived = false,
                            Niveau = "Troisieme",
                            Nom = "3ème"
                        },
                        new
                        {
                            Id = new Guid("162a342f-3e60-4452-89ea-23eea2881969"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "SECONDE",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3136),
                            IsArchived = false,
                            Niveau = "Seconde",
                            Nom = "2nde"
                        },
                        new
                        {
                            Id = new Guid("92d9a073-40d7-414b-a47a-074dcbdae334"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "PREMIERE",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3148),
                            IsArchived = false,
                            Niveau = "Premiere",
                            Nom = "1ère"
                        },
                        new
                        {
                            Id = new Guid("fc0a4a38-ffa1-458d-bc24-c8b55aee5083"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CapaciteMax = 60,
                            Code = "TERMINALE",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3158),
                            IsArchived = false,
                            Niveau = "Terminale",
                            Nom = "Tle"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClasseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactUrgence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupeSanguin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationalite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("FamilleId");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPere")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("NomMere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomPere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrenomMere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrenomPere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfessionMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionPere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuartierCommune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephonePere")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelephonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelephoneSecondaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Familles");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeFraisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("TypeFraisId");

                    b.ToTable("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Coefficient")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EleveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MatiereId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NoteSur")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("PeriodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnregistrePar")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroPaiement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnregistrePar");

                    b.HasIndex("FamilleId");

                    b.HasIndex("NumeroPaiement")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnneeScolaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.ToTable("Periodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2841351b-07d1-4a3f-b1d2-62a4dfc513b5"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 30, 149, DateTimeKind.Utc).AddTicks(3079),
                            DateDebut = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 1",
                            Numero = 1,
                            Type = "Trimestre"
                        },
                        new
                        {
                            Id = new Guid("6535e75b-5a42-41a7-ba0b-101e17f6cc0c"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 30, 149, DateTimeKind.Utc).AddTicks(3087),
                            DateDebut = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 2",
                            Numero = 2,
                            Type = "Trimestre"
                        },
                        new
                        {
                            Id = new Guid("f60dcc90-6857-4676-a875-72454318a99f"),
                            AnneeScolaireId = new Guid("a4d4d9e7-87cc-4f37-8cc5-903c2f633047"),
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 30, 149, DateTimeKind.Utc).AddTicks(3290),
                            DateDebut = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Libelle = "Trimestre 3",
                            Numero = 3,
                            Type = "Trimestre"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GenerationAutomatique")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsObligatoire")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MontantsParNiveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TypeFrais");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e33935ee-4e54-4079-9435-a242b52578f5"),
                            Categorie = "Inscription",
                            Code = "INSC",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3871),
                            GenerationAutomatique = true,
                            IsArchived = false,
                            IsObligatoire = true,
                            IsRecurrent = false,
                            Libelle = "Frais d'inscription",
                            MontantsParNiveau = "{\"CP\":5000,\"CE1\":5000,\"CE2\":5000,\"CM1\":5000,\"CM2\":5000,\"Sixieme\":5000,\"Cinquieme\":5000,\"Quatrieme\":5000,\"Troisieme\":5000,\"Seconde\":5000,\"Premiere\":5000,\"Terminale\":5000}"
                        },
                        new
                        {
                            Id = new Guid("5c2c6d83-8527-4cb2-9137-b4ef1e2e326d"),
                            Categorie = "Scolarite",
                            Code = "SCOL",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3881),
                            Description = "Frais de scolarité trimestriel",
                            GenerationAutomatique = true,
                            IsArchived = false,
                            IsObligatoire = true,
                            IsRecurrent = true,
                            Libelle = "Scolarité",
                            MontantsParNiveau = "{\"CP\":60000,\"CE1\":60000,\"CE2\":60000,\"CM1\":70000,\"CM2\":70000,\"Sixieme\":80000,\"Cinquieme\":80000,\"Quatrieme\":85000,\"Troisieme\":85000,\"Seconde\":90000,\"Premiere\":90000,\"Terminale\":90000}"
                        },
                        new
                        {
                            Id = new Guid("da911798-e028-4e5f-b336-acde0952f536"),
                            Categorie = "Cantine",
                            Code = "CANT",
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(3887),
                            Description = "Frais de cantine mensuel",
                            GenerationAutomatique = false,
                            IsArchived = false,
                            IsObligatoire = false,
                            IsRecurrent = true,
                            Libelle = "Cantine",
                            MontantsParNiveau = "{\"CP\":15000,\"CE1\":15000,\"CE2\":15000,\"CM1\":15000,\"CM2\":15000,\"Sixieme\":15000,\"Cinquieme\":15000,\"Quatrieme\":15000,\"Troisieme\":15000,\"Seconde\":15000,\"Premiere\":15000,\"Terminale\":15000}"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1fbae4e7-f95c-4ecb-9bdd-169cd25249f2"),
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 30, 889, DateTimeKind.Utc).AddTicks(4490),
                            Email = "admin@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Administrateur",
                            PasswordHash = "$2a$11$WnfisnWbQ239P3s20CxHAOXD9LzGw0uBSRUj5QOJbas8QS28lXOWy",
                            Prenom = "Système",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("7263be8a-5280-41c5-bf47-02fde17caf25"),
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 31, 501, DateTimeKind.Utc).AddTicks(9843),
                            Email = "directeur@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Durand",
                            PasswordHash = "$2a$11$KE8qdribrTrMECPBNiRDjOiVso74CTH2Onuo2hqOuZOELbR12L7Dq",
                            Prenom = "Marie",
                            Role = "Directeur",
                            Username = "directeur"
                        },
                        new
                        {
                            Id = new Guid("ae7087c6-46ad-4505-971d-57b01ccf02a6"),
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 0, DateTimeKind.Utc).AddTicks(7651),
                            Email = "comptable@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Martin",
                            PasswordHash = "$2a$11$IJj1SMplCTo94cHgxqR3bO8B4prCvQ3mGUo2nKcujWbTV6/jUGLfK",
                            Prenom = "Sophie",
                            Role = "Comptable",
                            Username = "comptable"
                        },
                        new
                        {
                            Id = new Guid("0f29a6df-a6cc-4a83-99ab-b6a484491776"),
                            CreatedAt = new DateTime(2025, 12, 26, 13, 54, 32, 654, DateTimeKind.Utc).AddTicks(1900),
                            Email = "secretaire@schoolflow.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsArchived = false,
                            Nom = "Leroy",
                            PasswordHash = "$2a$11$y7VLWUkDN3nGY4AEBaGKbOr9WX5BQAHKbEvrvYkKXSQHIUkDOYY8u",
                            Prenom = "Paul",
                            Role = "Secretaire",
                            Username = "secretaire"
                        });
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EleveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FraisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontantVentile")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaiementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarque")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("FraisId");

                    b.HasIndex("PaiementId");

                    b.ToTable("VentilationsPaiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Classes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Eleves")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SchoolFlow.Domain.Entities.Classe", "Classe")
                        .WithMany("Eleves")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Eleves")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Classe");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Frais")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.TypeFrais", "TypeFrais")
                        .WithMany("Frais")
                        .HasForeignKey("TypeFraisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Periode");

                    b.Navigation("TypeFrais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Note", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany("Notes")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SchoolFlow.Domain.Entities.Matiere", "Matiere")
                        .WithMany("Notes")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolFlow.Domain.Entities.Periode", "Periode")
                        .WithMany()
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Utilisateur", "EnregistreParUtilisateur")
                        .WithMany()
                        .HasForeignKey("EnregistrePar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Famille", "Famille")
                        .WithMany("Paiements")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnregistreParUtilisateur");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Periode", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Periodes")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.VentilationPaiement", b =>
                {
                    b.HasOne("SchoolFlow.Domain.Entities.Eleve", "Eleve")
                        .WithMany()
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolFlow.Domain.Entities.Frais", "Frais")
                        .WithMany("Ventilations")
                        .HasForeignKey("FraisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolFlow.Domain.Entities.Paiement", "Paiement")
                        .WithMany("Ventilations")
                        .HasForeignKey("PaiementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Frais");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.AnneeScolaire", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Eleves");

                    b.Navigation("Periodes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Classe", b =>
                {
                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Eleve", b =>
                {
                    b.Navigation("Frais");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Famille", b =>
                {
                    b.Navigation("Eleves");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Frais", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Matiere", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Paiement", b =>
                {
                    b.Navigation("Ventilations");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.TypeFrais", b =>
                {
                    b.Navigation("Frais");
                });

            modelBuilder.Entity("SchoolFlow.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
